// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWJj2Hhle8RdaLZOUSTe5WR6pAHiZagjc',
    appId: '1:1026698494114:web:339361e18c998050fe57fb',
    messagingSenderId: '1026698494114',
    projectId: 'my-crossnote-project',
    authDomain: 'my-crossnote-project.firebaseapp.com',
    storageBucket: 'my-crossnote-project.appspot.com',
    measurementId: 'G-C0GQFNJ3FH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA53adlQp-0T4BXM_clXb_NJUSkDZwHgFo',
    appId: '1:1026698494114:android:80cb0fe021975fdafe57fb',
    messagingSenderId: '1026698494114',
    projectId: 'my-crossnote-project',
    storageBucket: 'my-crossnote-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaYeP7HQElE5PKbTGgG3XGEMr8H36jd-g',
    appId: '1:1026698494114:ios:9c6bd1ea1e64f013fe57fb',
    messagingSenderId: '1026698494114',
    projectId: 'my-crossnote-project',
    storageBucket: 'my-crossnote-project.appspot.com',
    iosBundleId: 'com.flutterup21.crossnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaYeP7HQElE5PKbTGgG3XGEMr8H36jd-g',
    appId: '1:1026698494114:ios:5d4b027330bd0fe2fe57fb',
    messagingSenderId: '1026698494114',
    projectId: 'my-crossnote-project',
    storageBucket: 'my-crossnote-project.appspot.com',
    iosBundleId: 'com.flutterup21.crossnotes.RunnerTests',
  );
}
